name:                space-x-client
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- servant
- servant-client
- servant-client-core
- http-client
- http-client-tls
- aeson
- generic-aeson

default-extensions:
- OverloadedStrings

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  space-x-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - space-x-client

tests:
  space-x-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - space-x-client
    - hspec
    - hspec-discover
    - QuickCheck


verbatim:
  cabal-version: 3.0
